remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

title: "JTest Utils"
tagline: "A set of testing utilities for Java"
description: "Match JSON, XML and simple texts using matching conditions, regex and polling support"
author: "Florin Slevoaca"
url: "https://fslev.github.io/jtest-utils"
permalink: pretty